//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public Aula()
        {
            this.AlunoAula = new HashSet<AlunoAula>();
            this.EquipamentoAula = new HashSet<EquipamentoAula>();
        }
    
        public int idAula { get; set; }
        public string dsAula { get; set; }
        public int capacidade { get; set; }
        public string observacao { get; set; }
        public decimal preco { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public int idTpAula { get; set; }
    
        public virtual ICollection<AlunoAula> AlunoAula { get; set; }
        public virtual TpAula TpAula { get; set; }
        public virtual ICollection<EquipamentoAula> EquipamentoAula { get; set; }
    }
}
