//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Aluno = new HashSet<Aluno>();
            this.Fornecedor = new HashSet<Fornecedor>();
            this.Funcionario = new HashSet<Funcionario>();
        }

        [Display(Name="Código")]
        public int idCidade { get; set; }

        [Display(Name = "Descrição")]
        [StringLength(100, ErrorMessage="Descrição pode ter no máxiimo 100 caracteres!")]
        [Required(ErrorMessage = "Observação é obrigatória!")]
        public string dsCidade { get; set; }

        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> dtCriacao { get; set; }

        [Display(Name = "UF")]
        [Required(ErrorMessage = "UF é obrigatória!")]
        public int idUf { get; set; }

        [Display(Name = "Status")]
        public Nullable<byte> status { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual Uf Uf { get; set; }
        public virtual ICollection<Fornecedor> Fornecedor { get; set; }
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
