//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Venda = new HashSet<Venda>();
        }
    
        public int idCliente { get; set; }
        public string dsCliente { get; set; }
        public string cpfCnpj { get; set; }
        public string inscrEstadual { get; set; }
        public string rua { get; set; }
        public string bairro { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public int idCidade { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Venda> Venda { get; set; }
    }
}
