//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsertoEquipamento
    {
        public int idConserto { get; set; }
        public int idEquipamento { get; set; }
        public int qtdEquipamentos { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
    
        public virtual Conserto Conserto { get; set; }
        public virtual Equipamento Equipamento { get; set; }
    }
}
