//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamento
    {
        public Equipamento()
        {
            this.Compra = new HashSet<Compra>();
            this.EquipamentoAula = new HashSet<EquipamentoAula>();
            this.ExercicioEquipamento = new HashSet<ExercicioEquipamento>();
            this.Manutencao = new HashSet<Manutencao>();
            this.Venda = new HashSet<Venda>();
        }
    
        public int idEquipamento { get; set; }
        public string dsEquipamento { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public Nullable<byte> status_ { get; set; }
        public int idTpEquipamento { get; set; }
        public int idFornecedor { get; set; }
    
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual ICollection<EquipamentoAula> EquipamentoAula { get; set; }
        public virtual ICollection<ExercicioEquipamento> ExercicioEquipamento { get; set; }
        public virtual ICollection<Manutencao> Manutencao { get; set; }
        public virtual ICollection<Venda> Venda { get; set; }
    }
}
