//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.Compra = new HashSet<Compra>();
            this.Conserto = new HashSet<Conserto>();
            this.Equipamento = new HashSet<Equipamento>();
        }
    
        public int idFornecedor { get; set; }
        public string dsFornecedor { get; set; }
        public string cnpj { get; set; }
        public string inscrEstadual { get; set; }
        public string rua { get; set; }
        public string bairro { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public int idCidade { get; set; }
        public int idTpFornecedor { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Conserto> Conserto { get; set; }
        public virtual ICollection<Equipamento> Equipamento { get; set; }
        public virtual TpFornecedor TpFornecedor { get; set; }
    }
}
