//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Uf = new HashSet<Uf>();
        }
    
        public int idPais { get; set; }
        public string dsPais { get; set; }
        public string abrevPais { get; set; }
        public Nullable<byte> status { get; set; }
        public System.DateTime dtCriacao { get; set; }
    
        public virtual ICollection<Uf> Uf { get; set; }
    }
}
