//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Uf
    {
        public Uf()
        {
            this.Cidade = new HashSet<Cidade>();
        }

        [Display(Name = "Código")]
        public int idUf { get; set; }

        [Display(Name = "Descrição")]
        public string dsUf { get; set; }

        [Display(Name = "Abreviação")]
        public string abrevUf { get; set; }

        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> dtCriacao { get; set; }

        [Display(Name = "Status")]
        public Nullable<byte> status { get; set; }

        [Display(Name = "País")]
        public int idPais { get; set; }
    
        public virtual ICollection<Cidade> Cidade { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
