//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uf
    {
        public Uf()
        {
            this.Cidade = new HashSet<Cidade>();
        }
    
        public int idUf { get; set; }
        public string dsUf { get; set; }
        public string abrevUf { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public Nullable<byte> status { get; set; }
        public int idPais { get; set; }
    
        public virtual ICollection<Cidade> Cidade { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
