//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Aula
    {
        public Aula()
        {
            this.AlunoAula = new HashSet<AlunoAula>();
            this.EquipamentoAula = new HashSet<EquipamentoAula>();
        }

        [Display(Name = "Código")]
        public int idAula { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Nome é obrigatorio!")]
        [StringLength(100, ErrorMessage = "Nome deve ter no máximo 100 caracteres!")]
        public string dsAula { get; set; }

        [Display(Name = "Capacidade")]
        [Required(ErrorMessage = "Capacidade é obrigatoria!")]
        public int capacidade { get; set; }

        [Display(Name = "Observação")]
        [Required(ErrorMessage = "Observação é obrigatorio!")]
        [StringLength(200, ErrorMessage = "Observação deve ter no máximo 100 caracteres!")]
        public string observacao { get; set; }

        [Display(Name = "Preço")]
        [Required(ErrorMessage = "Preço é obrigatorio!")]
        public decimal preco { get; set; }

        [Display(Name = "Status")]
        public Nullable<byte> status { get; set; }

        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> dtCriacao { get; set; }

        [Display(Name = "Tipo Aula")]
        [Required(ErrorMessage = "Tipo de Aula é obrigatorio!")]
        public int idTpAula { get; set; }
    
        public virtual ICollection<AlunoAula> AlunoAula { get; set; }
        public virtual TpAula TpAula { get; set; }
        public virtual ICollection<EquipamentoAula> EquipamentoAula { get; set; }
    }
}
