//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Aluno = new HashSet<Aluno>();
            this.Fornecedor = new HashSet<Fornecedor>();
            this.Funcionario = new HashSet<Funcionario>();
        }
    
        public int idCidade { get; set; }
        public string dsCidade { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public int idUf { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual ICollection<Aluno> Aluno { get; set; }
        public virtual Uf Uf { get; set; }
        public virtual ICollection<Fornecedor> Fornecedor { get; set; }
        public virtual ICollection<Funcionario> Funcionario { get; set; }
    }
}
