//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Compra
    {
        [Display(Name = "Código")]
        public int idCompra { get; set; }

        [Display(Name = "Fornecedor")]
        [Required(ErrorMessage = "Fornecedor é obrigatório!")]
        public Nullable<int> idFornecedor { get; set; }

        [Display(Name = "Valor")]
        [Required(ErrorMessage = "Valor é obrigatório!")]
        public Nullable<decimal> valorCompra { get; set; }

        [Display(Name = "Parcelas")]
        [Required(ErrorMessage = "Quantidade de parcelas é obrigatória!")]
        public Nullable<int> qtdParcelas { get; set; }

        [Display(Name = "Data da Venda")]
        [Required(ErrorMessage = "Data da venda é obrigatória!")]
        public Nullable<System.DateTime> dtVenda { get; set; }

        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> dtCriacao { get; set; }

        [Display(Name = "Equipamento")]
        [Required(ErrorMessage = "Equipamento é obrigatório!")]
        public int idEquipamento { get; set; }
    
        public virtual Equipamento Equipamento { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
