//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conserto
    {
        public Conserto()
        {
            this.ConsertoEquipamento = new HashSet<ConsertoEquipamento>();
        }
    
        public int idConserto { get; set; }
        public int idFornecedor { get; set; }
        public int idTpConserto { get; set; }
        public decimal valorConserto { get; set; }
        public int qtdParcelas { get; set; }
        public System.DateTime dtConserto { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual TpConserto TpConserto { get; set; }
        public virtual ICollection<ConsertoEquipamento> ConsertoEquipamento { get; set; }
    }
}
