//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ContasPagar
    {
        [Display(Name="Código")]
        public int idContasPagar { get; set; }

        [Display(Name = "Descrição")]
        public string dsContasPagar { get; set; }

        [Display(Name = "Valor")]
        public decimal valor { get; set; }

        [Display(Name = "Data de Vencimento")]
        public System.DateTime dtVencimento { get; set; }

        [Display(Name = "Data de Pagamento")]
        public Nullable<System.DateTime> dtPagamento { get; set; }

        [Display(Name = "Código FK")]
        public Nullable<int> idTabelaFK { get; set; }

        [Display(Name = "Tipo de Contas a Pagar")]
        public Nullable<byte> tpRegistro { get; set; }
    }
}
