//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Exercicio
    {
        public Exercicio()
        {
            this.ExercicioEquipamento = new HashSet<ExercicioEquipamento>();
            this.Ficha = new HashSet<Ficha>();
        }

        [Display(Name = "Código")]
        public int idExercicio { get; set; }

        [Display(Name = "Descrição")]
        [StringLength(100, ErrorMessage = "Descrição não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Descrição é obrigatória!")]
        public string dsExercicio { get; set; }

        [Display(Name = "Observação")]
        [StringLength(200, ErrorMessage = "Observação não pode ter mais que 200 caracteres!")]
        [Required(ErrorMessage = "Observação é obrigatória!")]
        public string observacao { get; set; }

        [Display(Name = "Status")]
        public Nullable<byte> status { get; set; }

        [Display(Name = "Data de Criação")]
        public System.DateTime dtCriacao { get; set; }

        [Display(Name = "Tipo de Exercício")]
        [Required(ErrorMessage = "Tipo de exercício é obrigatório!")]
        public int idTpExercicio { get; set; }
    
        public virtual TpExercicio TpExercicio { get; set; }
        public virtual ICollection<ExercicioEquipamento> ExercicioEquipamento { get; set; }
        public virtual ICollection<Ficha> Ficha { get; set; }
    }
}
