//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercicio
    {
        public Exercicio()
        {
            this.ExercicioEquipamento = new HashSet<ExercicioEquipamento>();
            this.Ficha = new HashSet<Ficha>();
        }
    
        public int idExercicio { get; set; }
        public string dsExercicio { get; set; }
        public string observacao { get; set; }
        public Nullable<byte> status { get; set; }
        public System.DateTime dtCriacao { get; set; }
        public int idTpExercicio { get; set; }
    
        public virtual TpExercicio TpExercicio { get; set; }
        public virtual ICollection<ExercicioEquipamento> ExercicioEquipamento { get; set; }
        public virtual ICollection<Ficha> Ficha { get; set; }
    }
}
