//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        public Ficha()
        {
            this.HistExercicioAluno = new HashSet<HistExercicioAluno>();
        }
    
        public int idFicha { get; set; }
        public int idExercicio { get; set; }
        public int idAluno { get; set; }
        public int qtdRepeticoes { get; set; }
        public int series { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public byte status { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Exercicio Exercicio { get; set; }
        public virtual ICollection<HistExercicioAluno> HistExercicioAluno { get; set; }
    }
}
