//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.Compra = new HashSet<Compra>();
            this.Equipamento = new HashSet<Equipamento>();
            this.Manutencao = new HashSet<Manutencao>();
        }

        [Display(Name = "Fornecedor")]
        public int idFornecedor { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Nome é obrigatorio!")]
        [StringLength(100, ErrorMessage = "Nome deve ter no máximo 100 caracteres!")]
        public string dsFornecedor { get; set; }

        [Display(Name = "CNPJ")]
        [Required(ErrorMessage = "CNPJ é obrigatorio!")]
        [StringLength(20, ErrorMessage = "CNPJ deve ter no máximo 20 caracteres!")]
        public string cnpj { get; set; }

        [Display(Name = "Inscrição Estadual")]
        [StringLength(20, ErrorMessage = "Inscrição Estadual deve ter no máximo 20 caracteres!")]
        public string inscrEstadual { get; set; }

        [Display(Name = "Endereço")]
        [StringLength(100, ErrorMessage = "Endereço deve ter no máximo 100 caracteres!")]
        public string rua { get; set; }

        [Display(Name = "Bairro")]
        [StringLength(100, ErrorMessage = "Bairro deve ter no máximo 100 caracteres!")]
        public string bairro { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email é obrigatorio!")]
        [StringLength(100, ErrorMessage = "Email deve ter no máximo 100 caracteres!")]
        public string email { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "Telefone é obrigatorio!")]
        [StringLength(100, ErrorMessage = "Telefone deve ter no máximo 100 caracteres!")]
        public string telefone { get; set; }

        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> dtCriacao { get; set; }

        [Display(Name = "Cidade")]
        [Required(ErrorMessage = "Cidade é obrigatoria!")]
        public int idCidade { get; set; }

        [Display(Name = "Status")]
        public Nullable<byte> status { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Equipamento> Equipamento { get; set; }
        public virtual ICollection<Manutencao> Manutencao { get; set; }
    }
}
