//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.Compra = new HashSet<Compra>();
            this.Equipamento = new HashSet<Equipamento>();
            this.Manutencao = new HashSet<Manutencao>();
        }

        [Display(Name = "Código")]
        public int idFornecedor { get; set; }

        [Display(Name = "Descrição")]
        [StringLength(100, ErrorMessage = "Descrição não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Descrição é obrigatória!")]
        public string dsFornecedor { get; set; }

        [Display(Name = "CNPJ")]
        [StringLength(20, ErrorMessage = "CNPJ não pode ter mais que 20 caracteres!")]
        [Required(ErrorMessage = "CNPJ é obrigatório!")]
        public string cnpj { get; set; }

        [Display(Name = "Inscrição Estadual")]
        [StringLength(20, ErrorMessage = "Inscrição estadual não pode ter mais que 20 caracteres!")]
        [Required(ErrorMessage = "Inscrição estadual é obrigatória!")]
        public string inscrEstadual { get; set; }

        [Display(Name = "Endereço")]
        [StringLength(100, ErrorMessage = "Endereço não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Endereço é obrigatório!")]
        public string rua { get; set; }

        [Display(Name = "Bairro")]
        [StringLength(100, ErrorMessage = "Bairro não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Bairro é obrigatório!")]
        public string bairro { get; set; }

        [Display(Name = "E-mail")]
        [StringLength(100, ErrorMessage = "E-mail não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "E-mail é obrigatório!")]
        public string email { get; set; }

        [Display(Name = "Telefone")]
        [StringLength(20, ErrorMessage = "Telefone não pode ter mais que 20 caracteres!")]
        [Required(ErrorMessage = "Telefone é obrigatório!")]
        public string telefone { get; set; }

        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> dtCriacao { get; set; }

        [Display(Name = "Cidade")]
        [Required(ErrorMessage = "Cidade é obrigatória!")]
        public int idCidade { get; set; }

        [Display(Name = "Status")]
        public Nullable<byte> status { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Equipamento> Equipamento { get; set; }
        public virtual ICollection<Manutencao> Manutencao { get; set; }
    }
}
