//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.HistPgtoFuncionario = new HashSet<HistPgtoFuncionario>();
            this.HistSalarioFuncionario = new HashSet<HistSalarioFuncionario>();
        }

        [Display(Name = "Código")]
        public int idFuncionario { get; set; }

        [Display(Name = "Nome")]
        [StringLength(100, ErrorMessage = "Nome não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Nome é obrigatório!")]
        public string nome { get; set; }

        [Display(Name = "CPF")]
        [StringLength(20, ErrorMessage = "CPF não pode ter mais que 20 caracteres!")]
        [Required(ErrorMessage = "CPF é obrigatório!")]
        public string cpf { get; set; }

        [Display(Name = "Telefone")]
        [StringLength(20, ErrorMessage = "Telefone não pode ter mais que 20 caracteres!")]
        [Required(ErrorMessage = "Telefone é obrigatório!")]
        public string telefone { get; set; }

        [Display(Name = "E-mail")]
        [StringLength(100, ErrorMessage = "E-mail não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "E-mail é obrigatória!")]
        public string email { get; set; }

        [Display(Name = "Endereço")]
        [StringLength(100, ErrorMessage = "Endereço não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Endereço é obrigatório!")]
        public string rua { get; set; }

        [Display(Name = "Bairro")]
        [StringLength(100, ErrorMessage = "Bairro não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Bairro é obrigatório!")]
        public string bairro { get; set; }

        [Display(Name = "CEP")]
        [StringLength(9, ErrorMessage = "CEP não pode ter mais que 9 caracteres!")]
        [Required(ErrorMessage = "CEP é obrigatório!")]
        public string cep { get; set; }

        [Display(Name = "CTPS")]
        [StringLength(20, ErrorMessage = "CTPS não pode ter mais que 20 caracteres!")]
        [Required(ErrorMessage = "CTPS é obrigatório!")]
        public string ctps { get; set; }

        [Display(Name = "Sexo")]
        [StringLength(1, ErrorMessage = "Sexo deve ser M ou F!")]
        [Required(ErrorMessage = "Sexo é obrigatório!")]
        public string sexo { get; set; }

        [Display(Name = "Data de nascimento")]
        [Required(ErrorMessage = "Data de nascimento é obrigatória!")]
        public System.DateTime aniversario { get; set; }

        [Display(Name = "Data de Criação")]
        public Nullable<System.DateTime> dtCriacao { get; set; }

        [Display(Name = "Cidade")]
        public int idCidade { get; set; }

        [Display(Name = "Status")]
        public Nullable<byte> status { get; set; }

        [Display(Name = "Tipo de Funcionário")]
        [Required(ErrorMessage = "Tipo de funcionário é obrigatório!")]
        public int idTpFuncionario { get; set; }

        [Display(Name = "Login")]
        [StringLength(100, ErrorMessage = "Login não pode ter mais que 100 caracteres!")]
        [Required(ErrorMessage = "Login é obrigatório!")]
        public string login { get; set; }

        public string senha { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<HistPgtoFuncionario> HistPgtoFuncionario { get; set; }
        public virtual ICollection<HistSalarioFuncionario> HistSalarioFuncionario { get; set; }
    }
}
