//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistExercicioAluno
    {
        public int idHistExercicioAluno { get; set; }
        public int idFicha { get; set; }
        public int qtdRepeticoesVelha { get; set; }
        public int qtdRepeticoesNova { get; set; }
        public int seriesVelho { get; set; }
        public int seriesNovo { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
    
        public virtual Ficha Ficha { get; set; }
    }
}
