//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manutencao
    {
        public Manutencao()
        {
            this.ManutencaoEquipamento = new HashSet<ManutencaoEquipamento>();
        }
    
        public int idManutencao { get; set; }
        public int idFornecedor { get; set; }
        public int idTpManutencao { get; set; }
        public decimal valorManutencao { get; set; }
        public int qtdParcelas { get; set; }
        public System.DateTime dtManutencao { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual ICollection<ManutencaoEquipamento> ManutencaoEquipamento { get; set; }
    }
}
