//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpExercicio
    {
        public TpExercicio()
        {
            this.Exercicio = new HashSet<Exercicio>();
        }
    
        public int idTpExercicio { get; set; }
        public string dsTpExercicio { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
    
        public virtual ICollection<Exercicio> Exercicio { get; set; }
    }
}
