//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpFornecedor
    {
        public TpFornecedor()
        {
            this.Fornecedor = new HashSet<Fornecedor>();
        }
    
        public int idTpFornecedor { get; set; }
        public string dsTpFornecedor { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public Nullable<byte> status { get; set; }
    
        public virtual ICollection<Fornecedor> Fornecedor { get; set; }
    }
}
